# Generated by Django 2.0 on 2021-01-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20210120_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
